ARG DEBIAN_TAG
FROM debian:${DEBIAN_TAG}

# ensure local toolchain bins are preferred over distribution bins
ENV PATH=/usr/local/bin:$PATH

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        clang \
        curl \
        dpkg-dev \
        fonts-liberation \
        fonts-noto \
        fonts-noto-cjk \
        fonts-roboto \
        fontconfig \
        gcc \
        git \
        gnupg \
        groff \
        libbluetooth-dev \
        libbz2-dev \
        libc6-dev \
        libcairo2 \
        libdb-dev \
        libffi-dev \
        libgdbm-dev \
        libharfbuzz0b \
        libjpeg62-turbo \
        liblzma-dev \
        libncursesw5-dev \
        libpango-1.0-0 \
        libpangoft2-1.0-0 \
        libreadline-dev \
        librsvg2-bin \
        libsqlite3-dev \
        libssl-dev \
        libzstd-dev \
        make \
        netbase \
        python3 \
        python3-venv \
        python3-pip \
        ripgrep \
        texlive-full \
        tk-dev \
        tzdata \
        uuid-dev \
        wget \
        xz-utils \
        zlib1g-dev \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    fc-cache -fv

RUN set -eux; \
    pip install --break-system-packages xml2rfc

WORKDIR /toolchain
