FROM sakura-dev-tools:03-go

COPY --from=sakura-dev-tools:01a-pdf2htmlex-builder \
    /artifacts/bin/pdf2htmlEX \
    /usr/local/bin/pdf2htmlEX
COPY --from=sakura-dev-tools:01a-pdf2htmlex-builder \
    /artifacts/lib/ \
    /usr/local/lib/
COPY --from=sakura-dev-tools:01a-pdf2htmlex-builder \
    /artifacts/share/ \
    /usr/local/share/

RUN ldconfig
