ARG DEBIAN_TAG
FROM debian:${DEBIAN_TAG}

# ensure local toolchain bins are preferred over distribution bins
ENV PATH=/usr/local/bin:$PATH

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        autoconf \
        bash \
        ca-certificates \
        clang \
        curl \
        dpkg-dev \
        fontconfig \
        fonts-liberation \
        fonts-noto \
        fonts-noto-cjk \
        fonts-roboto \
        gcc \
        gettext \
        git \
        gnupg \
        groff \
        iproute2 \
        less \
        libbluetooth-dev \
        libbz2-dev \
        libc6-dev \
        libcairo2 \
        libcurl4-gnutls-dev \
        libdb-dev \
        libexpat1-dev \
        libffi-dev \
        libgdbm-dev \
        libharfbuzz0b \
        libjpeg62-turbo \
        liblzma-dev \
        libncursesw5-dev \
        libpango-1.0-0 \
        libpangoft2-1.0-0 \
        libpcre2-dev \
        libreadline-dev \
        librsvg2-bin \
        libsqlite3-dev \
        libssl-dev \
        libzstd-dev \
        make \
        netbase \
        openssl \
        python3 \
        python3-pip \
        python3-venv \
        ripgrep \
        sudo \
        texlive-full \
        tk-dev \
        tzdata \
        unzip \
        uuid-dev \
        wget \
        xz-utils \
        zlib1g-dev \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    fc-cache -fv; \
    find / -type f -iname '*.log' -delete 2>/dev/null || true


RUN set -eux; \
    pip install --break-system-packages xml2rfc

WORKDIR /toolchain
